version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB:$POSTGRES_DB
      - POSTGRES_USER:$POSTGRES_USER
      - POSTGRES_PASSWORD:$POSTGRES_PASSWORD
      - TZ:'GMT'
      - PGTZ:'GMT'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    ports:
      - '5432:5432'

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD:$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE:$MONGO_INITDB_DATABASE
    volumes:
      - mongo_data:/data/db
    networks:
      - db_network
    ports:
      - '27017:27017'

volumes:
  postgres_data:
  mongo_data:

networks:
  db_network: